#  _   _       _    _
# | \ | |     | |  | |
# |  \| | ___ | |__| |_   _ _ __   __ _  ___ _ __
# | . ` |/ _ \|  __  | | | | '_ \ / _` |/ _ \ '__|
# | |\  | (_) | |  | | |_| | | | | (_| |  __/ |
# |_| \_|\___/|_|  |_|\__,_|_| |_|\__, |\___|_|
#                                  __/ |
#                                 |___/

name: NoHunger
description: A plugin that disables hunger on your Pocketmine 5.0.0 server.
author: Diduhless
website: https://twitter.com/Diduhless
main: Diduhless\NoHunger\NoHunger
version: "1.0.1"
api: 5.0.0
